name: 'Dart Benchmark Action'
description:
  'A GitHub action to run benchmarks on Dart/Flutter projects and libraries.'
author: 'Luan Nico'

branding:
  icon: 'watch'
  color: 'blue'

runs:
  using: node20
  main: dist/index.js
