name: 'Dart Benchmark Action'
description:
  'A GitHub Action to run benchmarks on Dart/Flutter projects and libraries.'
author: 'Luan Nico'

branding:
  icon: 'watch'
  color: 'blue'

runs:
  using: node20
  main: dist/index.js

inputs:
  paths:
    description:
      'Comma-separated list of paths to directories of Dart projects containing
      benchmarks to run.'
    required: true
